### ISSUE TITLE
Use config from file

### ISSUE THREAD

**Issue by andreybleme** [andreybleme/theros#3]
Users should be able to store their configuration in a `theros.yaml` file, in order to avoid repeatedly typing commands.

```yaml
default:
  root: 'build/'

production:
  key: 'XXX'
  secret: 'XXX'
  bucket: 'theros.io'

development:
  key: 'XXX'
  secret: 'XXX'
  bucket: 'theros-dev.io'
```
